---
- name: Linein sudoers file
  ansible.builtin.lineinfile:
    path: "{{ sudo_sudoers }}"
    regexp: "{{ sudoers_lineinfile_item.regexp | default(omit) }}"
    state: "{{ sudoers_lineinfile_item.state | default(omit) }}"
    line: "{{ sudoers_lineinfile_item.line | default(omit) }}"
    backup: "{{ sudoers_lineinfile_item.backup | default(omit) }}"
    validate: "{{ sudo_visudo }} -cf %s"
  with_items: "{{ sudoers_linesinfile | default([]) }}"
  loop_control:
    loop_var: sudoers_lineinfile_item
